package com.svi.accountchecker.constants;

public enum AccountClassAndType {
	INDIVIDUAL_ACTIVE, INDIVIDUAL_DORMANT, INDIVIDUAL_CLOSED,
	INSTITUTIONAL_ACTIVE, INSTITUTIONAL_DORMANT, INSTITUTIONAL_CLOSED;
}
